function selectedRunGroups = findSelectedRunGroups(runGroupsParametersTable,desiredChannel,responseType,queryParameters)

    if nargin == 3; queryParameters = []; end

    if strcmp(responseType,'excitatory'); holdingVoltage = -70;
    elseif strcmp(responseType,'inhibitory'); holdingVoltage = 0;
    elseif strcmp(responseType,'both'); holdingVoltage = -35;
    elseif strcmp(responseType,'none'); selectedRunGroups = []; return;
    else; disp('Response type not configured'); end

    if strcmp(desiredChannel,'blue')

        if ~isfield(queryParameters,'activeChannelsBlue'); queryParameters.activeChannelsBlue = 'ao0, ao1'; end
        if ~isfield(queryParameters,'holdingVoltageBlue'); queryParameters.holdingVoltageBlue = holdingVoltage; end
        if ~isfield(queryParameters,'amplitudeBlue'); queryParameters.amplitudeBlue = 5; end
        if ~isfield(queryParameters,'pulseWidthBlue'); queryParameters.pulseWidthBlue = 100; end
        if ~isfield(queryParameters,'functionNameBlue'); queryParameters.functionNameBlue = 'dmdOutputRect(1, 1, 1, 1, 1, 1)'; end
                
        if ~isfield(queryParameters,'scopeMagnification'); queryParameters.scopeMagnification = '40X'; end
        if ~isfield(queryParameters,'generalDrugs'); queryParameters.generalDrugs = []; end
        if ~isfield(queryParameters,'specificDrugs'); queryParameters.specificDrugs = 'NONE'; end
        if ~isfield(queryParameters,'cellLocation'); queryParameters.cellLocation = []; end
        if ~isfield(queryParameters,'cellTemperature'); queryParameters.cellTemperature = 24; end
        if ~isfield(queryParameters,'cellType'); queryParameters.cellType = []; end

        selectedRunGroups = find(strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannelsBlue) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageBlue & ...
            cell2mat(runGroupsParametersTable.amplitudeBlue) == queryParameters.amplitudeBlue & ...
            cell2mat(runGroupsParametersTable.pulseWidthBlue) == queryParameters.pulseWidthBlue & ...
            strcmp(runGroupsParametersTable.functionNameBlue,queryParameters.functionNameBlue) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...              
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType)))));

    elseif strcmp(desiredChannel,'red')
        
        if ~isfield(queryParameters,'activeChannelsRed'); queryParameters.activeChannelsRed = 'ao0, ao2'; end
        if ~isfield(queryParameters,'holdingVoltageRed'); queryParameters.holdingVoltageRed = holdingVoltage; end
        if ~isfield(queryParameters,'amplitudeRed'); queryParameters.amplitudeRed = 5; end
        if ~isfield(queryParameters,'pulseWidthRed'); queryParameters.pulseWidthRed = 100; end
        if ~isfield(queryParameters,'functionNameRed'); queryParameters.functionNameRed = 'dmdOutputRect(1, 1, 1, 1, 2, 1)'; end

        if ~isfield(queryParameters,'scopeMagnification'); queryParameters.scopeMagnification = '40X'; end
        if ~isfield(queryParameters,'generalDrugs'); queryParameters.generalDrugs = []; end
        if ~isfield(queryParameters,'specificDrugs'); queryParameters.specificDrugs = 'NONE'; end
        if ~isfield(queryParameters,'cellLocation'); queryParameters.cellLocation = []; end
        if ~isfield(queryParameters,'cellTemperature'); queryParameters.cellTemperature = 24; end
        if ~isfield(queryParameters,'cellType'); queryParameters.cellType = []; end
        
        selectedRunGroups = find(strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannelsRed) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageRed & ...
            cell2mat(runGroupsParametersTable.amplitudeRed) == queryParameters.amplitudeRed & ...
            cell2mat(runGroupsParametersTable.pulseWidthRed) == queryParameters.pulseWidthRed & ...
            strcmp(runGroupsParametersTable.functionNameRed,queryParameters.functionNameRed) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...     
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType)))));
    
    elseif strcmp(desiredChannel,'blue|red')
            
        if ~isfield(queryParameters,'activeChannelsBlue'); queryParameters.activeChannelsBlue = 'ao0, ao1'; end
        if ~isfield(queryParameters,'activeChannelsRed'); queryParameters.activeChannelsRed = 'ao0, ao2'; end
        if ~isfield(queryParameters,'holdingVoltageBlue'); queryParameters.holdingVoltageBlue = holdingVoltage; end
        if ~isfield(queryParameters,'holdingVoltageRed'); queryParameters.holdingVoltageRed = holdingVoltage; end
        if ~isfield(queryParameters,'amplitudeBlue'); queryParameters.amplitudeBlue = 5; end
        if ~isfield(queryParameters,'amplitudeRed'); queryParameters.amplitudeRed = 5; end
        if ~isfield(queryParameters,'pulseWidthBlue'); queryParameters.pulseWidthBlue = 100; end
        if ~isfield(queryParameters,'pulseWidthRed'); queryParameters.pulseWidthRed = 100; end
        if ~isfield(queryParameters,'functionNameBlue'); queryParameters.functionNameBlue = 'dmdOutputRect(1, 1, 1, 1, 1, 1)'; end
        if ~isfield(queryParameters,'functionNameRed'); queryParameters.functionNameRed = 'dmdOutputRect(1, 1, 1, 1, 2, 1)'; end

        if ~isfield(queryParameters,'scopeMagnification'); queryParameters.scopeMagnification = '40X'; end
        if ~isfield(queryParameters,'generalDrugs'); queryParameters.generalDrugs = []; end
        if ~isfield(queryParameters,'specificDrugs'); queryParameters.specificDrugs = 'NONE'; end
        if ~isfield(queryParameters,'cellLocation'); queryParameters.cellLocation = []; end
        if ~isfield(queryParameters,'cellTemperature'); queryParameters.cellTemperature = 24; end
        if ~isfield(queryParameters,'cellType'); queryParameters.cellType = []; end

        selectedRunGroups = find((strcmp(runGroupsParametersTable.responseType,responseType)) & ...                
            ((strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannelsBlue) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageBlue & ...
            cell2mat(runGroupsParametersTable.amplitudeBlue) == queryParameters.amplitudeBlue & ...
            cell2mat(runGroupsParametersTable.pulseWidthBlue) == queryParameters.pulseWidthBlue & ...
            strcmp(runGroupsParametersTable.functionNameBlue,queryParameters.functionNameBlue) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...              
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType)))) | ...              
            (strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannelsRed) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageRed & ...
            cell2mat(runGroupsParametersTable.amplitudeRed) == queryParameters.amplitudeRed & ...
            cell2mat(runGroupsParametersTable.pulseWidthRed) == queryParameters.pulseWidthRed & ...
            strcmp(runGroupsParametersTable.functionNameRed,queryParameters.functionNameRed) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...     
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType))))))));

    elseif strcmp(responseType,'both')
        
        if ~isfield(queryParameters,'activeChannels'); queryParameters.activeChannels = 'ao0, ao1, ao2'; end
        if ~isfield(queryParameters,'holdingVoltageBlue'); queryParameters.holdingVoltageBlue = holdingVoltage; end
        if ~isfield(queryParameters,'holdingVoltageRed'); queryParameters.holdingVoltageRed = holdingVoltage; end
        if ~isfield(queryParameters,'amplitudeBlue'); queryParameters.amplitudeBlue = 5; end
        if ~isfield(queryParameters,'amplitudeRed'); queryParameters.amplitudeRed = 5; end
        if ~isfield(queryParameters,'pulseWidthBlue'); queryParameters.pulseWidthBlue = 100; end
        if ~isfield(queryParameters,'pulseWidthRed'); queryParameters.pulseWidthRed = 100; end
        if ~isfield(queryParameters,'functionNameBlue'); queryParameters.functionNameBlue = 'dmdOutputRect(1, 1, 1, 1, 1, 1)'; end
        if ~isfield(queryParameters,'functionNameRed'); queryParameters.functionNameRed = 'dmdOutputRect(1, 1, 1, 1, 2, 1)'; end

        if ~isfield(queryParameters,'scopeMagnification'); queryParameters.scopeMagnification = '40X'; end
        if ~isfield(queryParameters,'generalDrugs'); queryParameters.generalDrugs = []; end
        if ~isfield(queryParameters,'specificDrugs'); queryParameters.specificDrugs = 'NONE'; end
        if ~isfield(queryParameters,'cellLocation'); queryParameters.cellLocation = []; end
        if ~isfield(queryParameters,'cellTemperature'); queryParameters.cellTemperature = 24; end
        if ~isfield(queryParameters,'cellType'); queryParameters.cellType = []; end

        selectedRunGroups = find((strcmp(runGroupsParametersTable.responseType,responseType)) & ...                
            ((strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannels) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageBlue & ...
            cell2mat(runGroupsParametersTable.amplitudeBlue) == queryParameters.amplitudeBlue & ...
            cell2mat(runGroupsParametersTable.pulseWidthBlue) == queryParameters.pulseWidthBlue & ...
            strcmp(runGroupsParametersTable.functionNameBlue,queryParameters.functionNameBlue) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...              
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType)))) & ...              
            (strcmp(runGroupsParametersTable.activeChannels,queryParameters.activeChannels) & ...
            cell2mat(runGroupsParametersTable.holdingVoltage) == queryParameters.holdingVoltageRed & ...
            cell2mat(runGroupsParametersTable.amplitudeRed) == queryParameters.amplitudeRed & ...
            cell2mat(runGroupsParametersTable.pulseWidthRed) == queryParameters.pulseWidthRed & ...
            strcmp(runGroupsParametersTable.functionNameRed,queryParameters.functionNameRed) & ...
            ((isempty(queryParameters.scopeMagnification)) | (strcmp(runGroupsParametersTable.scopeMagnification,queryParameters.scopeMagnification))) & ...
            ((isempty(queryParameters.generalDrugs)) | (strcmp(runGroupsParametersTable.generalDrugs,queryParameters.generalDrugs))) & ...
            ((isempty(queryParameters.specificDrugs)) | (strcmp(runGroupsParametersTable.specificDrugs,queryParameters.specificDrugs))) & ...     
            ((isempty(queryParameters.cellLocation)) | (strcmp(runGroupsParametersTable.cellLocation,queryParameters.cellLocation))) & ...
            ((isempty(queryParameters.cellTemperature)) | (cell2mat(runGroupsParametersTable.cellTemperature) == queryParameters.cellTemperature) & ...
            ((isempty(queryParameters.cellType)) | (strcmp(runGroupsParametersTable.cellType,queryParameters.cellType))))))));

    end

end
